import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import ts from "typescript"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(scriptDir, "..")
const generatedFilePath = join(repoRoot, "util/generatedBoardOnlyPropNames.ts")
const virtualFilePath = join(repoRoot, "scripts/__extract_board_props__.ts")

const sourceText = `
  import type { BoardProps, ChipProps } from "@tscircuit/props"
  type BoardOnlyProps = Omit<BoardProps, keyof ChipProps>
`

const compilerOptions: ts.CompilerOptions = {
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Node10,
  skipLibCheck: true,
  strict: true,
  target: ts.ScriptTarget.ESNext,
}

const defaultHost = ts.createCompilerHost(compilerOptions)
const host: ts.CompilerHost = {
  ...defaultHost,
  fileExists: (fileName) =>
    fileName === virtualFilePath || defaultHost.fileExists(fileName),
  readFile: (fileName) =>
    fileName === virtualFilePath ? sourceText : defaultHost.readFile(fileName),
  getSourceFile: (
    fileName,
    languageVersion,
    onError,
    shouldCreateNewSourceFile,
  ) =>
    fileName === virtualFilePath
      ? ts.createSourceFile(fileName, sourceText, languageVersion, true)
      : defaultHost.getSourceFile(
          fileName,
          languageVersion,
          onError,
          shouldCreateNewSourceFile,
        ),
}

const program = ts.createProgram([virtualFilePath], compilerOptions, host)
const checker = program.getTypeChecker()
const sourceFile = program.getSourceFile(virtualFilePath)

if (!sourceFile) {
  throw new Error(
    "Unable to create virtual source file for board prop extraction",
  )
}

const boardOnlyTypeAlias = sourceFile.statements.find(
  (statement): statement is ts.TypeAliasDeclaration =>
    ts.isTypeAliasDeclaration(statement) &&
    statement.name.text === "BoardOnlyProps",
)

if (!boardOnlyTypeAlias) {
  throw new Error("Unable to find BoardOnlyProps type alias")
}

const boardOnlyType = checker.getTypeFromTypeNode(boardOnlyTypeAlias.type)
const boardOnlyPropNames = checker
  .getPropertiesOfType(boardOnlyType)
  .map((property) => property.getName())
  .sort((a, b) => a.localeCompare(b))

if (boardOnlyPropNames.length === 0) {
  throw new Error("No board-only props were extracted from @tscircuit/props")
}

const generatedSource = `// This file is generated by scripts/generate-board-only-prop-names.ts.
// Do not edit manually.

export const boardOnlyPropNames = ${JSON.stringify(boardOnlyPropNames, null, 2)} as const

export type BoardOnlyPropName = (typeof boardOnlyPropNames)[number]
`

writeFileSync(generatedFilePath, generatedSource)
